PORT: 8066
# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 10"
  - "ios >= 7"

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "../resources/static"
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "src/fonts/**/*"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
  # Paths to JavaScript entry points for webpack to bundle modules
  entries:
    - "js/main.js"
